---
- name: Installing HTTPD Package on FrontEnd Server {{ inventory_hostname }}
  package:
   name: httpd
   state: latest
- name: Installing HAProxy Package on FrontEnd Server {{ inventory_hostname }}
  yum:
   name: haproxy 
   state: latest
- name: Enable HAProxy on FrontEnd Server {{ inventory_hostname }}
  service:
   name: haproxy
  notify:
    - start_haproxy
- name: Configure haproxy on FrontEnd Server {{ inventory_hostname }}
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
- name: Restart HAproxy on FrontEnd Server {{ inventory_hostname }}
  service:
   name: haproxy
  notify: 
    - restart_haproxy
